blank_issues_enabled: false
contact_links:
  - name: â“ Ask a Question
    url: https://github.com/faiyazkhan024/sandbox/discussions
    about: Use this link if you have a question about this project.
  - name: ğŸ” Report a Security Vulnerability
    url: https://github.com/faiyazkhan024/sandbox/security/advisories
    about: Report security vulnerabilities privately via this link.
